// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {skills} from '../models';
import {main} from '../models';
import {store} from '../models';
import {upstream} from '../models';

export function AddKimiAPIKey(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AddKimiFromJWT(arg1:string):Promise<Record<string, any>>;

export function CancelAutoSignup():Promise<void>;

export function CancelChat():Promise<void>;

export function CancelDeviceLogin():Promise<void>;

export function CreateSkill(arg1:string,arg2:string,arg3:string):Promise<skills.Skill>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function GetAccountGoogleCredentials(arg1:string):Promise<string|string>;

export function GetActiveRequest():Promise<main.ActiveRequest>;

export function GetAutoCreateOnExhausted():Promise<boolean>;

export function GetBootstrap():Promise<Record<string, any>>;

export function GetDeviceLoginState():Promise<main.deviceLoginState>;

export function GetGoogleCredentials():Promise<string|string>;

export function GetKimiStealthHeadless():Promise<boolean>;

export function GetSettings():Promise<store.Settings>;

export function GetSkill(arg1:string):Promise<skills.Skill>;

export function GetStats():Promise<Record<string, any>>;

export function GetUsage():Promise<Record<string, store.UsageTotals>>;

export function IsSignupRunning():Promise<boolean>;

export function ListAccounts():Promise<Array<Record<string, any>>>;

export function ListAccountsForProvider(arg1:string):Promise<Array<Record<string, any>>>;

export function ListMCPServers():Promise<Array<Record<string, any>>>;

export function ListModels():Promise<Array<upstream.ModelInfo>>;

export function ListProviders():Promise<Array<Record<string, any>>>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function LogoffKimiAccount(arg1:string):Promise<Record<string, any>>;

export function OpenExternal(arg1:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RenameAccount(arg1:string,arg2:string):Promise<void>;

export function SendChat(arg1:upstream.ChatRequest):Promise<void>;

export function SetAccountGoogleCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function SetAutoCreateOnExhausted(arg1:boolean):Promise<void>;

export function SetGoogleCredentials(arg1:string,arg2:string):Promise<void>;

export function SetKimiStealthHeadless(arg1:boolean):Promise<void>;

export function StartAutoSignup():Promise<void>;

export function StartDeviceLogin():Promise<main.deviceLoginState>;

export function StartKimiBrowserLogin():Promise<Record<string, any>>;

export function StartKimiStealthLogin(arg1:boolean):Promise<Record<string, any>>;

export function StartKimiStealthLoginForAccount(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function StartKimiStealthLoginNewAccount(arg1:boolean):Promise<Record<string, any>>;

export function SyncGrokCLI():Promise<Record<string, any>>;

export function UpdateSettings(arg1:Record<string, any>):Promise<store.Settings>;

export function UpdateSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skills.Skill>;

export function UpsertMCPServer(arg1:Record<string, any>):Promise<Record<string, any>>;
