// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKimiAPIKey(arg1, arg2) {
  return window['go']['main']['App']['AddKimiAPIKey'](arg1, arg2);
}

export function AddKimiFromJWT(arg1) {
  return window['go']['main']['App']['AddKimiFromJWT'](arg1);
}

export function CancelAutoSignup() {
  return window['go']['main']['App']['CancelAutoSignup']();
}

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function CancelDeviceLogin() {
  return window['go']['main']['App']['CancelDeviceLogin']();
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetActiveRequest() {
  return window['go']['main']['App']['GetActiveRequest']();
}

export function GetAutoCreateOnExhausted() {
  return window['go']['main']['App']['GetAutoCreateOnExhausted']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetDeviceLoginState() {
  return window['go']['main']['App']['GetDeviceLoginState']();
}

export function GetGoogleCredentials() {
  return window['go']['main']['App']['GetGoogleCredentials']();
}

export function GetKimiStealthHeadless() {
  return window['go']['main']['App']['GetKimiStealthHeadless']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function IsSignupRunning() {
  return window['go']['main']['App']['IsSignupRunning']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListAccountsForProvider(arg1) {
  return window['go']['main']['App']['ListAccountsForProvider'](arg1);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function LogoffKimiAccount(arg1) {
  return window['go']['main']['App']['LogoffKimiAccount'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SetAutoCreateOnExhausted(arg1) {
  return window['go']['main']['App']['SetAutoCreateOnExhausted'](arg1);
}

export function SetGoogleCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetGoogleCredentials'](arg1, arg2);
}

export function SetKimiStealthHeadless(arg1) {
  return window['go']['main']['App']['SetKimiStealthHeadless'](arg1);
}

export function StartAutoSignup() {
  return window['go']['main']['App']['StartAutoSignup']();
}

export function StartDeviceLogin() {
  return window['go']['main']['App']['StartDeviceLogin']();
}

export function StartKimiBrowserLogin() {
  return window['go']['main']['App']['StartKimiBrowserLogin']();
}

export function StartKimiStealthLogin(arg1) {
  return window['go']['main']['App']['StartKimiStealthLogin'](arg1);
}

export function SyncGrokCLI() {
  return window['go']['main']['App']['SyncGrokCLI']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}

export function UpsertMCPServer(arg1) {
  return window['go']['main']['App']['UpsertMCPServer'](arg1);
}
