// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelChat() {
  return window['go']['main']['App']['CancelChat']();
}

export function CancelDeviceLogin() {
  return window['go']['main']['App']['CancelDeviceLogin']();
}

export function CreateAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2);
}

export function CreateAccountFromDevice() {
  return window['go']['main']['App']['CreateAccountFromDevice']();
}

export function CreateAccounts(arg1) {
  return window['go']['main']['App']['CreateAccounts'](arg1);
}

export function CreateSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetActiveRequest() {
  return window['go']['main']['App']['GetActiveRequest']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetDeviceLoginState() {
  return window['go']['main']['App']['GetDeviceLoginState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function ImportSSO(arg1) {
  return window['go']['main']['App']['ImportSSO'](arg1);
}

export function ImportSSOFromFile(arg1) {
  return window['go']['main']['App']['ImportSSOFromFile'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RecoverAccounts() {
  return window['go']['main']['App']['RecoverAccounts']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameAccount(arg1, arg2) {
  return window['go']['main']['App']['RenameAccount'](arg1, arg2);
}

export function ResetAccount(arg1) {
  return window['go']['main']['App']['ResetAccount'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartDevice() {
  return window['go']['main']['App']['StartDevice']();
}

export function StartDeviceLogin() {
  return window['go']['main']['App']['StartDeviceLogin']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2, arg3, arg4);
}

export function UpsertMCPServer(arg1) {
  return window['go']['main']['App']['UpsertMCPServer'](arg1);
}
