// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {register} from '../models';
import {skills} from '../models';
import {main} from '../models';
import {store} from '../models';
import {upstream} from '../models';

export function CancelChat():Promise<void>;

export function CancelDeviceLogin():Promise<void>;

export function CreateAccount(arg1:string,arg2:string):Promise<register.Result>;

export function CreateAccountFromDevice():Promise<register.Result>;

export function CreateAccounts(arg1:number):Promise<Array<Record<string, any>>>;

export function CreateSkill(arg1:string,arg2:string,arg3:string):Promise<skills.Skill>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function GetActiveRequest():Promise<main.ActiveRequest>;

export function GetBootstrap():Promise<Record<string, any>>;

export function GetDeviceLoginState():Promise<main.deviceLoginState>;

export function GetSettings():Promise<store.Settings>;

export function GetSkill(arg1:string):Promise<skills.Skill>;

export function GetStats():Promise<Record<string, any>>;

export function GetUsage():Promise<Record<string, store.UsageTotals>>;

export function ImportSSO(arg1:string):Promise<Record<string, any>>;

export function ImportSSOFromFile(arg1:string):Promise<Record<string, any>>;

export function ListAccounts():Promise<Array<Record<string, any>>>;

export function ListMCPServers():Promise<Array<Record<string, any>>>;

export function ListModels():Promise<Array<upstream.ModelInfo>>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function OpenExternal(arg1:string):Promise<void>;

export function RecoverAccounts():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RenameAccount(arg1:string,arg2:string):Promise<void>;

export function ResetAccount(arg1:string):Promise<void>;

export function SendChat(arg1:upstream.ChatRequest):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function StartDevice():Promise<Record<string, string>>;

export function StartDeviceLogin():Promise<main.deviceLoginState>;

export function UpdateSettings(arg1:Record<string, any>):Promise<store.Settings>;

export function UpdateSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skills.Skill>;

export function UpsertMCPServer(arg1:Record<string, any>):Promise<Record<string, any>>;
